#!/bin/sh
# Custom Docker entrypoint for FrankenPHP-based PHP image
# Handles UID/GID mapping, PHP configuration, and session setup

set -e

# ---------------------------------------------------------------------------
# 1. UID/GID Mapping
# ---------------------------------------------------------------------------
# If PUID or PGID are set, update the www-data user/group to match.
# This is useful for matching host filesystem permissions in development.

if [ -n "${PGID}" ]; then
    echo "entrypoint: Setting www-data group ID to ${PGID}"
    groupmod -o -g "${PGID}" www-data
fi

if [ -n "${PUID}" ]; then
    echo "entrypoint: Setting www-data user ID to ${PUID}"
    usermod -o -u "${PUID}" www-data
fi

# ---------------------------------------------------------------------------
# 2. Write PHP configuration
# ---------------------------------------------------------------------------
# Generate a single ini file from environment variables with sensible defaults.

cat > /usr/local/etc/php/conf.d/zz-docker.ini <<EOF
; Auto-generated by entrypoint.sh — do not edit manually

; --- Resource Limits ---
memory_limit = ${PHP_MEMORY_LIMIT:-512M}
upload_max_filesize = ${PHP_UPLOAD_MAX_SIZE:-20M}
post_max_size = ${PHP_UPLOAD_MAX_SIZE:-20M}

; --- Error Handling ---
display_errors = ${PHP_DISPLAY_ERRORS:-Off}
display_startup_errors = ${PHP_DISPLAY_STARTUP_ERRORS:-Off}
error_reporting = ${PHP_ERROR_REPORTING:-E_ALL & ~E_DEPRECATED & ~E_STRICT}
log_errors = ${PHP_LOG_ERRORS:-On}
error_log = ${PHP_ERROR_LOG:-/dev/stderr}

; --- Execution Limits ---
max_execution_time = ${PHP_MAX_EXECUTION_TIME:-30}
max_input_time = ${PHP_MAX_INPUT_TIME:-60}
max_input_vars = ${PHP_MAX_INPUT_VARS:-1000}

; --- OPcache ---
opcache.enable = ${PHP_OPCACHE_ENABLE:-1}
opcache.memory_consumption = ${PHP_OPCACHE_MEMORY:-128}
opcache.max_accelerated_files = ${PHP_OPCACHE_MAX_FILES:-10000}
opcache.validate_timestamps = ${PHP_OPCACHE_VALIDATE_TIMESTAMPS:-0}
opcache.revalidate_freq = ${PHP_OPCACHE_REVALIDATE_FREQ:-0}
opcache.save_comments = ${PHP_OPCACHE_SAVE_COMMENTS:-1}
opcache.jit = ${PHP_OPCACHE_JIT:-disable}
opcache.jit_buffer_size = ${PHP_OPCACHE_JIT_BUFFER_SIZE:-0}

; --- Session ---
session.save_handler = ${PHP_SESSION_HANDLER:-files}
session.save_path = ${PHP_SESSION_SAVE_PATH:-/tmp/sessions}
session.cookie_secure = ${PHP_SESSION_COOKIE_SECURE:-1}

; --- Other ---
date.timezone = ${PHP_TIMEZONE:-UTC}
realpath_cache_size = ${PHP_REALPATH_CACHE_SIZE:-4096K}
realpath_cache_ttl = ${PHP_REALPATH_CACHE_TTL:-600}
expose_php = ${PHP_EXPOSE_PHP:-Off}
serialize_precision = ${PHP_SERIALIZE_PRECISION:--1}
zend.assertions = ${PHP_ZEND_ASSERTIONS:--1}
EOF

# Append OPcache preload settings only when a preload script is specified
if [ -n "${PHP_OPCACHE_PRELOAD}" ]; then
    cat >> /usr/local/etc/php/conf.d/zz-docker.ini <<EOF

; --- OPcache Preload ---
opcache.preload = ${PHP_OPCACHE_PRELOAD}
opcache.preload_user = ${PHP_OPCACHE_PRELOAD_USER:-www-data}
EOF
fi

# ---------------------------------------------------------------------------
# 3. Create session directory
# ---------------------------------------------------------------------------
SESSION_DIR="${PHP_SESSION_SAVE_PATH:-/tmp/sessions}"
mkdir -p "${SESSION_DIR}"
chown www-data:www-data "${SESSION_DIR}"
chmod 700 "${SESSION_DIR}"

# ---------------------------------------------------------------------------
# 4. Hand off to the original entrypoint
# ---------------------------------------------------------------------------
if command -v docker-php-entrypoint >/dev/null 2>&1; then
    exec docker-php-entrypoint "$@"
else
    exec "$@"
fi
